apiVersion: v1
kind: Secret
metadata:
  name: essrc-kube-prometheus-stack-prometheus-scrape-confg
  namespace: monitoring
stringData: # Use stringData to avoid base64 encoding issues
  essrc-additional-scrape-configs.yaml: |
    - job_name: 'essrc-blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]  # Look for a HTTP 200 response.
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115  # The blackbox exporter's real hostname:port.
        - target_label: location
          replacement: 'ESSRC'
      static_configs:
        - targets:
            - https://spsrc25.iaa.csic.es/  # Target to probe with https.
          labels:
            servicename: 'spsrc25'
        - targets:
            - https://spsrc26.iaa.csic.es/  # Target to probe with https.
          labels:
            servicename: 'spsrc26'
