##################################################
#                                                #
#                    AUSSRC                      #
#                                                #
##################################################

- job_name: aussrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: AUSSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: aussrc
  #   targets:
  #   - https://aussrc.example.com/


##################################################
#                                                #
#                    CANSRC                      #
#                                                #
##################################################

- job_name: cansrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: CANSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: cansrc
  #   targets:
  #   - https://cansrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.cansrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.cansrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.cansrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.cansrc.org/


##################################################
#                                                #
#                    CHSRC                      #
#                                                #
##################################################

- job_name: chsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: CHSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: chsrc
  #   targets:
  #   - https://chsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.chsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.chsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.chsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.chsrc.org/

  - labels:
      servicename: skaha
    targets:
    - http://skaha.src.skach.org/

  - labels:
      servicename: harbor
    targets:
    - http://harbor.dev.skach.org/

  - labels:
      servicename: echo
    targets:
    - https://echo.dev.skach.org/


##################################################
#                                                #
#                    CNSRC                      #
#                                                #
##################################################

- job_name: cnsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: CNSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: cnsrc
  #   targets:
  #   - https://cnsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.cnsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.cnsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.cnsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.cnsrc.org/


##################################################
#                                                #
#                    DESRC                      #
#                                                #
##################################################

- job_name: desrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: DESRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: desrc
  #   targets:
  #   - https://desrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.desrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.desrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.desrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.desrc.org/


##################################################
#                                                #
#                    ESPSRC                      #
#                                                #
##################################################

- job_name: espsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: ESPSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: espsrc
  #   targets:
  #   - https://espsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.espsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.espsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.espsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.espsrc.org/

  - labels:
      servicename: spsrc25
    targets:
    - https://spsrc25.iaa.csic.es/

  - labels:
      servicename: spsrc26
    targets:
    - https://spsrc26.iaa.csic.es/


##################################################
#                                                #
#                    FRSRC                      #
#                                                #
##################################################

- job_name: frsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: FRSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: frsrc
  #   targets:
  #   - https://frsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.frsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.frsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.frsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.frsrc.org/


##################################################
#                                                #
#                    INSRC                      #
#                                                #
##################################################

- job_name: insrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: INSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: insrc
  #   targets:
  #   - https://insrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.insrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.insrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.insrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.insrc.org/


##################################################
#                                                #
#                    ITRSRC                      #
#                                                #
##################################################

- job_name: itrsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: ITRSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: itrsrc
  #   targets:
  #   - https://itrsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.itrsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.itrsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.itrsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.itrsrc.org/


##################################################
#                                                #
#                    JPSRC                      #
#                                                #
##################################################

- job_name: jpsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: JPSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: jpsrc
  #   targets:
  #   - https://jpsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.jpsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.jpsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.jpsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.jpsrc.org/


##################################################
#                                                #
#                    NLRC                       #
#                                                #
##################################################

- job_name: nlrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: NLRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: nlrc
  #   targets:
  #   - https://nlrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.nlrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.nlrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.nlrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.nlrc.org/


##################################################
#                                                #
#                    PLRSC                      #
#                                                #
##################################################

- job_name: plrsc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: PLRSC
  static_configs:
  ## example:
  # - labels:
  #     servicename: plrsc
  #   targets:
  #   - https://plrsc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.plrsc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.plrsc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.plrsc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.plrsc.org/


##################################################
#                                                #
#                    PRSRC                      #
#                                                #
##################################################

- job_name: prsrc-blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  - target_label: location
    replacement: PRSRC
  static_configs:
  ## example:
  # - labels:
  #     servicename: prsrc
  #   targets:
  #   - https://prsrc.example.com/

  - labels:
      servicename: rucio-storage-element
    targets:
    # - https://rucio.prsrc.org/

  - labels:
      servicename: jupyterhub
    targets:
    # - https://jupyterhub.prsrc.org/

  - labels:
      servicename: perfsonar
    targets:
    # - https://perfsonar.prsrc.org/

  - labels:
      servicename: gatekeeper-api
    targets:
    # - https://gatekeeper.prsrc.org/
