apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml

# Patching of regular resources
patches:
  - path: namespace-label-patch.yaml
    target:
      version: v1
      kind: Namespace
      name: ska-src-gatekeeper-echo
  - path: ../../base/remove-resolver-patch.yaml
    target:
      kind: Ingress

# Helm chart definition with values overlay
helmCharts:
  - name: ska-src-service-gatekeeper
    repo: https://gitlab.com/api/v4/projects/61396570/packages/helm/stable
    version: 0.0.3
    namespace: gatekeeper
    # base values file
    valuesFile: ../../base/values.yaml
    # overlay values file that will override the base
    additionalValuesFiles:
      - values.yaml
    releaseName: gatekeeper
