hub:
  extraEnv:
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: jupyterhub
          key: CLIENT_SECRET
  config:
    Authenticator:
      enable_auth_state: true
      allow_all: true
    GenericOAuthenticator:
      login_service: "SKA-IAM"
      authorize_url: https://ska-iam.stfc.ac.uk/authorize
      token_url: https://ska-iam.stfc.ac.uk/token
      userdata_url: https://ska-iam.stfc.ac.uk/userinfo
      scope:
        - openid
        - profile
        - email
        - offline_access
      userdata_token_method: GET
      userdata_params: { "state": "state" }
      username_key: preferred_username
    JupyterHub:
      authenticator_class: generic-oauth
    BinderSpawner:
      auth_enabled: true
  extraVolumes: # innovation-day
    - name: sqlite-db
      persistentVolumeClaim:
        claimName: jupyterhub-shared-db-pvc
  extraVolumeMounts: # innovation-day
    - name: sqlite-db
      mountPath: /mnt/sqlite
  extraConfig: # innovation-day
    preSpawnHook: |
      def pre_spawn_hook(spawner):
        import os
        import sqlite3

        db_dir = "/mnt/sqlite"
        db_path = os.path.join(db_dir, "user_data.db")

        # Check if the database exists
        if not os.path.exists(db_path):
            raise Exception(f"Database not found at {db_path}")

        # Connect to SQLite DB
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # Get subPaths for the user
        cursor.execute("SELECT sub_path FROM sub_paths WHERE user_name = ?", (spawner.user.name,))
        sub_paths = [row[0] for row in cursor.fetchall()]
        conn.close()

        # Mount subPaths dynamically under /home/jovyan
        for sub_path in sub_paths:
            volume_mount = {
                "mountPath": f"/home/jovyan/{sub_path}",
                "subPath": f"deterministic/{sub_path}",
                "name": "rse-volume",
                "readOnly": True,
            }
            spawner.volume_mounts.append(volume_mount)

      c.KubeSpawner.pre_spawn_hook = pre_spawn_hook
  db:
    pvc:
      storageClassName: ceph-corbo-rbd-hdd

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  pathSuffix: ""
  pathType: Prefix

proxy:
  service:
    type: ClusterIP

singleuser:
  image:
    name: quay.io/jupyter/minimal-notebook
    tag: notebook-7.2.2
  memory:
    limit:
    guarantee: 1G
  cpu:
    limit:
    guarantee:
  profileList:
    - display_name: "Minimal environment"
      description: "Python environment."
      default: true
  storage:
    capacity: 10Gi
    dynamic:
      storageClass: ceph-corbo-rbd-hdd
    extraVolumes:
      - name: rse-volume
        persistentVolumeClaim:
          claimName: jupyterhub-rse-pvc
    # extraVolumeMounts:
    #   - name: rse-volume
    #     mountPath: /home/jovyan/rse
    #     subPath: deterministic
    #     readOnly: true
    # extraVolumes:
    #   - name: <name>
    # extraVolumeMounts: # do we need to mount additional volumes, e.g. to read&write "large" data products?
    #   - name: <name>
    #   - mountPath: <path>
  cmd: null # allows custom cmd for jupyter docker-stacks to be used for startup customization
  # memory:
  #   guarantee: 1G  # current default [3.3.8 - 07-24]
  # networkPolicy:
  #   allowedIngressPorts: [ssh]  # allow ssh &| sftp?
  cloudMetadata:
    blockWithIptables: false
  extraNodeAffinity:
    required: # only gets considered if `scheduling.userPods.nodeAffinity.matchNodePurpose: require`
      - matchExpressions:
          - key: "hpc"
            operator: "In"
            values:
              - "true"

scheduling:
  userPods:
    tolerations:
      - key: "hpc"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "hpc"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
    nodeAffinity:
      matchNodePurpose: require
