apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://gitlab.com/ska-telescope/src/deployments/chsrc/ska-src-chsrc-services-cd.git
      targetRevision: prod
      ref: argorepo
      path: apps/jupyterhub/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        field.cattle.io/projectId: c-m-g4gg2jck:p-z6jsk
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
