apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: any-ingress # this name doesn't exist, but the field is necessary. Patch will apply to all ingresses.
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
            resolver rke2-coredns-rke2-coredns.kube-system.svc.cluster.local ipv6=off valid=30s;
            lua_ssl_verify_depth 3;
            lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

            location ~* "/ping" {
                default_type text/plain;
                return 200 'OK';
            }