apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper
  namespace: gatekeeper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gatekeeper
    namespace: gatekeeper
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gatekeeper
  namespace: gatekeeper
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "app"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "gatekeeper"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "gatekeeper"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatekeeper
  namespace: gatekeeper
spec:
  refreshInterval: "15s" # time to sync from vault
  secretStoreRef:
    name: gatekeeper
    kind: SecretStore
  target:
    name: client-credentials # This secret HAS to have the name that matches the .Values.ingress-nginx.controller.extraVolumes client-credentials volume
    creationPolicy: Owner # create secret if not exists
  data:
    - secretKey: client_id
      remoteRef:
        key: app/data/gatekeeper # path to secret in vault
        property: client_id # key in the vault secret
    - secretKey: client_secret
      remoteRef:
        key: app/data/gatekeeper # path to secret in vault
        property: client_secret # key in the vault secret