apiVersion: v1
kind: ConfigMap
metadata:
  name: xrootd-http-config
  namespace: xrootd
data:
  xrootd-http.cfg: |
    # The export directive indicates which paths are to be exported. While the
    # default is '/tmp', we indicate it anyway to show you this directive.
    #
    #all.export /tmp
    all.export /data

    # The adminpath and pidpath variables indicate where the pid and various
    # IPC files should be placed
    #
    all.adminpath /var/spool/xrootd
    all.pidpath /run/xrootd

    xrd.protocol XrdHttp libXrdHttp.so
    # More configuration files can be added in /etc/xrootd/config.d/
    # For example /etc/xrootd/config.d/10-mygrid.cfg and
    # /etc/xrootd/config.d/98-mysite-specifics.cfg
    #
    # Config TLS
    xrd.tls /etc/grid-security/xrd/tls.crt /etc/grid-security/xrd/tls.key
    xrd.tlsca certdir /etc/grid-security/certificates refresh 8h
    xrootd.tls capable all -data
  
    # Enable checksum support
    xrootd.chksum adler32

    # Config tokens
    xrootd.seclib libXrdSec.so
    sec.level all compatible

    # More configuration files can be added in /etc/xrootd/config.d/
    # For example /etc/xrootd/config.d/10-mygrid.cfg and
    # /etc/xrootd/config.d/98-mysite-specifics.cfg

    # Authentication and Authorisation part
    ofs.authorize 1
    ofs.authlib ++ libXrdAccSciTokens.so config=/etc/xrootd/scitokens.cfg
    ofs.authlib ++ libXrdMacaroons.so
    acc.authdb /etc/xrootd/Authfile
    acc.audit deny
    acc.authrefresh 60

    # Pass the bearer token to the Xrootd authorization framework.
    http.header2cgi Authorization authz

    # Only for debugging (comment out after setup is done)
    scitokens.trace all
    ofs.trace all
    pfc.trace all
    xrd.trace all -sched
    pss.setopt DebugLevel 5

    all.sitename CHSRC-RSE

    # Enable third-party-copy
    http.exthandler xrdtpc libXrdHttpTPC.so
  scitokens.cfg: |
    [Global]
    onmissing = passthrough

    [Issuer ESCAPE IAM]
    issuer =  https://iam-escape.cloud.cnaf.infn.it/
    base_path = /data
    map_subject = false
    default_user = xrootd

    [Issuer SKA-IAM]
    issuer = https://ska-iam.stfc.ac.uk/
    base_path = /data
    map_subject = false
    default_user = xrootd

  Authfile: |
    # Grant access to all directories below '/data/'
    g * /data a
