apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xrootd-data-pvc
  namespace: xrootd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-corbo-rbd-hdd-retain