apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: monitoring
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: monitoring
  namespace: monitoring
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "app"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "monitoring"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "monitoring"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring  # Change to the appropriate namespace if needed
spec:
  refreshInterval: "15s"  # Time to sync from Vault
  secretStoreRef:
    name: monitoring  # Change to your SecretStore name
    kind: SecretStore
  target:
    name: grafana-ska-iam-secret  # Name of the Kubernetes Secret to be created
    creationPolicy: Owner  # Create secret if it does not exist
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: app/data/grafana  # Path to the secret in Vault
        property: GF_AUTH_GENERIC_OAUTH_CLIENT_ID  # Key in the Vault secret
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: app/data/grafana
        property: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
---
