{
 "title": "Central Monitoring / Global Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Core Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "# DDM & Monitoring" },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "content": "# AuthN/Z" },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "content": "# IVOA" },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Rucio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "computed_columns": [
      {
       "selector": "version==\"1.29.6\" ? \"UP\" : \"DOWN\"",
       "text": "status",
       "type": "string"
      }
     ],
     "expr": "last_over_time(probe_success{servicename=\"rucio\"}[$__interval])",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://rucio.srcdev.skao.int/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "IAM (SKA)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" }
     ],
     "expr": "last_over_time(probe_success{location=\"global\", servicename=\"ska-iam\"}[10m])",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://ska-iam.stfc.ac.uk/actuator/health",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "IVOA / TAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "obs_id", "text": "obs_id", "type": "string" }
     ],
     "csv_options": { "delimiter": "," },
     "expr": "probe_success{location=\"global\", servicename=\"ivoa-tap\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "url": "https://dachs.ivoa.srcdev.skao.int/__system__/tap/run/sync?REQUEST=doQuery&LANG=ADQL&FORMAT=CSV&QUERY=SELECT TOP 1 * FROM ivoa.obscore",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Monitoring / Grafana",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" }
     ],
     "expr": "last_over_time(probe_success{servicename=\"grafana\", location=\"global\"}[$__interval])",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://monit.srcdev.skao.int/elastic/_cluster/health",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "IVOA / Datalink ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" },
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "expr": "probe_success{location=\"global\", servicename=\"ivoa-datalink\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://datalink.ivoa.srcdev.skao.int/rucio/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Data Management",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" },
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "expr": "probe_success{location=\"global\", servicename=\"data-management-api\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://data-management.srcdev.skao.int/api/v1/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Site Capabilities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" },
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "expr": "probe_success{location=\"global\", servicename=\"site-capabilities-api\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://site-capabilities.srcdev.skao.int/api/v1/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Permissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" },
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "expr": "probe_success{location=\"global\", servicename=\"permissions-api\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://permissions.srcdev.skao.int/api/v1/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "status", "text": "status", "type": "string" },
      { "selector": "version", "text": "version", "type": "string" }
     ],
     "expr": "probe_success{location=\"global\", servicename=\"auth-api\"}",
     "legendFormat": "__auto",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://authn.srcdev.skao.int/api/v1/ping",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{location=\"global\"}",
     "legendFormat": "{{servicename}}"
    }
   ]
  }
 ]
}