apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

secretGenerator:
- name: grafana-alerting-secret
  envs:
  - grafana-alert.txt

resources:
- secrets.yaml
- srcnet-nodes-dashboards.yaml
<<<<<<< HEAD
- global-monitoring-dashboard.yaml
=======
- grafana-alerts.yaml
>>>>>>> 7593b73 (CHOC-161: Add grafana alerts to resources to be deployed)
