{
 "title": "Central Monitoring / SRCNet Site Services",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sitename",
    "label": "sitename",
    "query": "AUSSRC, CANSRC, CHSRC, CNSRC, DESRC, ESPSRC, FRSRC, INSRC, ITSRC, JPSRC, KRSRC, NLSRC, PTSRC, SWESRC, UKSRC, ZASRC"
   },
   { "name": "environment", "label": "environment", "query": "prod, dev" },
   { "name": "service", "label": "Service", "query": { "query": "label_values(servicename)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(probe_success{location=~\".+\", environment=\"$environment\", servicename=~\"gatekeeper|jupyterhub|science-portal|cavern|perfsonar|rucio-storage-element\"}[10m])",
     "legendFormat": "{{servicename}}"
    }
   ]
  },
  { "title": "Site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$sitename Services: Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job, servicename, environment, instance, location) (avg_over_time(probe_success{location=\"$sitename\", servicename=~\".+\", environment=\"$environment\"}[$__range])) * 100",
     "legendFormat": "{{servicename}}"
    }
   ]
  },
  {
   "title": "$sitename Services: Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(environment, job, location, servicename) (probe_success{location=\"$sitename\", servicename=~\".+\", environment=\"$environment\"})",
     "legendFormat": "{{servicename}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "last_over_time(probe_success{location=~\"$sitename\", environment=\"$environment\", servicename=~\".*\"}[10m])",
     "legendFormat": "{{servicename}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$sitename: Probe Duration Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(environment, job, location, servicename, phase) (\r\n  probe_duration_seconds{location=\"$sitename\", servicename=~\".*\", environment=\"$environment\"}\r\n)\r\nunless\r\nsum by(environment, job, location, servicename, phase) (\r\n  probe_success{location=\"$sitename\", servicename=~\".*\", environment=\"$environment\"} == 0\r\n)\r\n",
     "legendFormat": "{{servicename}} {{phase}}"
    }
   ]
  },
  {
   "title": "$sitename $service: HTTP Phases Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(environment, job, location, servicename, phase) (probe_http_duration_seconds{location=\"$sitename\", servicename=~\"$service\", environment=\"$environment\"})",
     "legendFormat": "{{servicename}} {{phase}}"
    }
   ]
  }
 ]
}