apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo-kustomized
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.com/ska-telescope/src/ska-chsrc-gitops.git
    targetRevision: choc-69-kustomize
    ref: argorepo
    path: applications/http-echo-kustomized/overlays/dev
    # important: do NOT set directory: beneath here when using kustomize,
    # otherwise ArgoCD will interpret all files as raw kubernetes manifests instead of kustomize resources
  destination:
    server: https://kubernetes.default.svc
    namespace: http-echo-kustomized
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
