apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: oci://registry-1.docker.io/bitnamicharts/thanos
    chart: thanos
    targetRevision: 15.7.17
    helm:
      valueFiles:
      - '$argorepo/applications/thanos/values.yaml'
  # We need to define this repo again using the multiple sources pattern.
  # This is necessary when using a values.yaml and a Helm chart that live on different repositories.
  # https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  # An alternative option would be to use an umbrella chart with the target helm chart as a dependency:
  # https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency
  - repoURL: https://gitlab.com/ska-telescope/src/ska-chsrc-gitops.git
    targetRevision: choc-33-thanos
    ref: argorepo
    path: applications/thanos
    directory:
      exclude: 'values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: thanos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
