apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.com/ska-telescope/src/ska-chsrc-gitops.git
    targetRevision: main
    ref: argorepo
    path: applications/vault
    directory:
      recurse: false
      exclude: 'values.yaml'
      include: '*.yaml'
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      valueFiles:
      - '$argorepo/applications/vault/values.yaml'
  # We need to define this repo again using the multiple sources pattern.
  # This is necessary when using a values.yaml and a Helm chart that live on different repositories.
  # https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  # An alternative option would be to use an umbrella chart with the target helm chart as a dependency:
  # https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency
  - repoURL: https://gitlab.com/ska-telescope/src/ska-chsrc-gitops.git
    targetRevision: main
    ref: argorepo
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
