apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xrootd-cephfs-pvc
  namespace: xrootd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-corbo-cephfs-retain