apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace is managed by the helmChart, and defining one here using the same name would cause a conflict error

resources:
- ../../base

# Helm chart definition with values overlay
helmCharts:
  - name: slurm-operator
    repo: oci://ghcr.io/slinkyproject/charts
    version: 0.1.0
    namespace: slinky
    # base values file
    valuesFile: ../../base/values.yaml
    # overlay values file that will override the base
    additionalValuesFiles:
      - values.yaml
