apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace is managed by the helmChart, and defining one here using the same name would cause a conflict error

resources:
- ../../base
- certificate.yaml

# Helm chart definition with values overlay
helmCharts:
  - name: base
    repo: https://images.opencadc.org/chartrepo/platform
    version: 0.3.3
    namespace: skaha-system
    releaseName: skaha-base
    # base values file
    valuesFile: ../../base/values-base.yaml
    # overlay values file that will override the base
    #additionalValuesFiles:
    #  - values-base.yaml
  - name: posixmapper
    repo: https://images.opencadc.org/chartrepo/platform
    version: 0.1.9
    namespace: skaha-system
    releaseName: skaha-posixmapper
    # base values file
    valuesFile: ../../base/values-posixmapper.yaml
    # overlay values file that will override the base
    #additionalValuesFiles:
    #  - values-posixmapper.yaml
  - name: skaha
    repo: https://images.opencadc.org/chartrepo/platform
    version: 0.8.1
    namespace: skaha-system
    releaseName: skaha
    # base values file
    valuesFile: ../../base/values-skaha.yaml
    # overlay values file that will override the base
    #additionalValuesFiles:
    #  - values-posixmapper.yaml

# Patching of regular resources
patches:
  # Patches the ingress to use the cert provided by cert-manager
  - path: posixmapper-cert.yaml
  # The posixmapper postgres password comes from the values.yaml :(
  # To use our secret from Vault we need to change two things:
  # 1. The postgres deployment, so that it uses our secret. This is the easy one as we can se the secret via env.
  # 2. The tomcat application. This is the tricky one because it expects the secret to appear in the /config/catalina.properties file.
  # 
  # The following patch ensures that the catalina.properties file is patched so that the postgres password is substituted with
  # the value that comes from our secret. This is implemented via an initContainer that runs envsubst to do the replacement.
  # It assumes that the password is set to an env expression ${POSTGRES_PASSWORD}.
  - target:
      version: v1
      kind: Deployment
      name: posix-mapper-tomcat
    path: ../../base/posix-mapper-tomcat-deployment-patch.yaml
  # The following two patches ensure the postgres deployment uses POSTGRES_PASSWORD env from the secret, not from the configmap as defined by Helm.
  - target:
      version: v1
      kind: Deployment
      name: posix-mapper-postgres
    path: ../../base/postgres-deploy-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: posix-mapper-postgres-config
    path: ../../base/remove-postgres-password-from-configmap-patch.yaml
  #### skaha patches ####
  - path: skaha-cert.yaml
  #### scienceportal patches ####
  # Patches the scienceportal ingress to use the cert provided by cert-manager
  - path: scienceportal-cert.yaml
  # Patches the cadc-registry.properties file in the science-portal-config ConfigMap and the science-portal-tomcat Deployment accordingly.
  # While the helm chart provides an `existingSecretName`, this relies on a lookup at helm template generation time,
  # which doesn't work without heavily patching ArgoCD as the reposerver doesn't have (by design) access to Kubernetes.
  - target:
      version: v1
      kind: Deployment
      name: science-portal-tomcat
    path: ../../base/science-portal-tomcat-deployment-patch.yaml
