# strategicMergePatch for the science portal ingress, as it's not supported by the helm chart
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: science-portal-ingress
  namespace: skaha-system
spec:
  tls:
  - hosts:
    - skaha.dev.skach.org
    secretName: skaha.dev.skach.org