apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soda

resources:
  - ../../base
  - soda-rse-storage.yaml

patches:
  - target:
      kind: Deployment
      name: ska-src-soda
    path: ../../base/pvc-patch.yaml

helmCharts:
  - name: ska-src-soda
    repo: https://gitlab.com/api/v4/projects/61599309/packages/helm/stable
    version: 0.0.1
    namespace: soda
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values.yaml
