apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-pvc
  namespace: soda
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-corbo-cephfs
