apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-echo
  namespace: http-echo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: http-echo-vault-access
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: http-echo
    namespace: http-echo
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: http-echo
  namespace: http-echo
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "app"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "http-echo"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "http-echo"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: http-echo
  namespace: http-echo
spec:
  refreshInterval: "15s" # time to sync from vault
  secretStoreRef:
    name: http-echo
    kind: SecretStore
  target:
    name: http-echo-example-secret-from-vault
    creationPolicy: Owner # create secret if not exists
  data:
    - secretKey: example-secret
      remoteRef:
        key: app/data/http-echo # path to secret in vault
        property: example-secret # key in the vault secret