---
text: "Hello SKACH"
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: echo.dev.skach.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - echo.dev.skach.org
        secretName: echo.dev.skach.org