apiVersion: apps/v1
kind: Deployment
metadata:
  name: posix-mapper-postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skaha-secrets
                  key: postgres-password