apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-corbo-rbd-hdd-retain
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
