- op: add
  path: /spec/template/spec/initContainers
  value:
    - name: patch-secrets
      image: envsubst/envsubst
      command:
        - "sh"
        - "-c"
        - |
          cp /config/* /patched-config/ && \
          cp /patched-config/org.opencadc.science-portal.properties /patched-config/org.opencadc.science-portal.properties.orig && \
          envsubst < /patched-config/org.opencadc.science-portal.properties.orig > /patched-config/org.opencadc.science-portal.properties
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: skaha-secrets
              key: oidc-client-secret
      volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: patched-config
          mountPath: /patched-config

- op: replace
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    mountPath: "/config"
    name: patched-config

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: patched-config
    emptyDir: {}
