apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-pvc
  namespace: skaha-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-corbo-cephfs-retain
