apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: http-echo
  namespace: http-echo
spec:
  dnsNames:
    - echo.dev.skach.org
  secretName: echo.dev.skach.org
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer