apiVersion: v1
kind: Namespace
metadata:
  name: skaha-system
  labels:
    field.cattle.io/projectId: p-z6jsk
---
apiVersion: v1
kind: Namespace
metadata:
  name: skaha-workload
  labels:
    field.cattle.io/projectId: p-z6jsk