apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana.dev.skach.org
  namespace: monitoring
spec:
  dnsNames:
    - grafana.dev.skach.org
  secretName: grafana.dev.skach.org
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
