---
grafana:
  ingress:
    hosts:
      - grafana.dev.skach.org
    tls:
      - secretName: grafana.dev.skach.org
        hosts:
          - grafana.dev.skach.org
  grafana.ini:
    server:
      root_url: https://grafana.dev.skach.org
alertmanager:
  config:
    global:
      # The secret value will be mounted in /etc/alertmanager/secrets/secret-name/key
      slack_api_url_file: '/etc/alertmanager/secrets/slack-api-url/slack-api-url'
    route:
      - receiver: 'slack-dev'
        matchers:
          - alertname = "ProbeFailure"
          - environment = "dev"
      # TODO: When SOG decides naming convention, create prod channel
      # TODO: When there is a prod channel, move to prod overlay
      - receiver: 'slack-dev'
        matchers:
          - alertname = "ProbeFailure"
          - environment = "prod"
    receivers:
      - name: 'slack-dev'
        slack_configs:
        - channel: '#chsrc-alerts-dev'
          send_resolved: true
          title: >
            {{ if eq .Status "resolved" }}
            :white_check_mark: Service {{ .CommonLabels.servicename }} in {{ .CommonLabels.location }} {{ .CommonLabels.environment }} has recovered
            {{ else }}
            :alert: Service {{ .CommonLabels.servicename }} in {{ .CommonLabels.location }} {{ .CommonLabels.environment }} is down
            {{ end }}
          title_link: 'https://grafana.dev.skach.org/d/site_specific_services/central-monitoring-srcnet-site-services?orgId=1'
          text: >
            {{ if eq .Status "resolved" }}
            *Note*: Click title for Grafana dashboard.
            The service has recovered and is back online.
            *Instance*: {{ .CommonLabels.instance }} {{ .CommonLabels.environment }}
            {{ else }}
            *Note*: Click title for Grafana dashboard. This message can be customized.
            *Instance*: {{ .CommonLabels.instance }} {{ .CommonLabels.environment }}
            {{ end }}
      # TODO: When there is a prod channel, move to prod overlay
      - name: 'slack-prod'
        slack_configs:
        - channel: '#chsrc-alerts-dev'
          send_resolved: true
          title: >
            {{ if eq .Status "resolved" }}
            :white_check_mark: Service {{ .CommonLabels.servicename }} in {{ .CommonLabels.location }} {{ .CommonLabels.environment }} has recovered
            {{ else }}
            :alert: Service {{ .CommonLabels.servicename }} in {{ .CommonLabels.location }} {{ .CommonLabels.environment }} is down
            {{ end }}
          title_link: 'https://grafana.src.skach.org/d/site_specific_services/central-monitoring-srcnet-site-services?orgId=1'
          text: |
            {{ if eq .Status "resolved" }}
            *Note*: Click title for Grafana dashboard.
            The service has recovered and is back online.
            *Instance*: {{ .CommonLabels.instance }} {{ .CommonLabels.environment }}
            {{ else }}
            *Note*: Click title for Grafana dashboard. This message can be customized.
            *Instance*: {{ .CommonLabels.instance }} {{ .CommonLabels.environment }}
            {{ end }}
