apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-redirect
  namespace: cluster-resources
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  ingressClassName: nginx
  rules: # This list will be fully replaced in each overlay
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-service  # You can use any dummy service here
            port:
              number: 80