apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-redirect
  namespace: cluster-resources
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
spec:
  ingressClassName: nginx
  rules: # This list will be fully replaced in each overlay
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-redirect
  namespace: cluster-resources
spec:
  secretName: docs-redirect
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer