apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rox-pvc
  namespace: soda
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-corbo-cephfs
  dataSource:
    name: rwx-pvc
    kind: PersistentVolumeClaim
