image:
  tag: 1.6.2

persistence:
  existingClaim: "soda-rse-pvc"
  enabled: true

affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "hpc"
            operator: "In"
            values:
              - "true"
